---
config:
  theme: base
---
flowchart LR
    subgraph L["Local Computer"]
        U["Browser"]
    end
    subgraph MM["MCP Marketplace"]
        M["MCP Tool Server"]
    end
    subgraph R["Remote Server"]
        A["Agent Server"]
        MM
        IS["Internal Services<br>(e.g. Database、MQ)"]
        IA["Internal APIs"]
    end
    U -- HTTP or WebSocket --> A
    A -- MCP Protocol<br>(SSE、Streamable) --> M
M -- Service Calls --> IS
M -- API Calls --> IA

M@{ shape: procs}
